### ISSUE TITLE
Grid View has 4 per row instead of 5

### ISSUE THREAD

**Issue by tr4656** [tr4656/SGUserstyle#2]
Probably by minor padding.

**Comment by tr4656** [comment]
Only on first page

**Comment by dewa710** [comment]
i am using firefox
for me the first page hast always 4 per row, but the others have 4 or 5
![Screenshot](https://dl.dropboxusercontent.com/u/41069083/sg_dark/grid2.jpg)

**Comment by SquishedPotatoe** [comment]
Here is what i did for this issue.

Changed .post
.post {
//    border: 1px solid #292a2e !important;
//    border-bottom: 1px solid #292a2e !important;
//    background: #212121 !important;
      padding-left: 2px !important;
}

Changed .post . right
.post .right {
    background: #333;
    border: 1px solid #444 !important;
    border-radius: 5px 5px 5px 5px;
    padding: 4px !important;
}

Removed second .post that contained.
.post { margin-right: 0px !important;}

**Comment by dewa710** [comment]
thank you SquishedPotatoe,
your solution helped for both of my issues :)

**Comment by SquishedPotatoe** [comment]
I only use grid view so that works fine but if you like to use both a better solution would be.

Changed .post
.post {
border: 1px solid #292a2e !important;
border-bottom: 1px solid #292a2e !important;
background: #212121 !important;
margin:1px -1px 1px -1px !important;
}

Changed .post . right
.post .right {
background: #333;
border: 1px solid #444 !important;
border-radius: 5px 5px 5px 5px;
}

Removed second .post that contained.
.post { margin-right: 0px !important;}

**Comment by tr4656** [comment]
Cool, that seemed to work Squashed Potatoe. Thanks a lot! I merged that in already/
